set-option -g prefix C-t
unbind C-b
bind C-t send-prefix

# Start panes at 1 not 0
setw -g pane-base-index 1
# Start windows at 1 not 0
set -g base-index 1
set -g renumber-windows on

# Some tweaks to the status line
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"
set -g status-position top
set -g pane-border-status off
set -g set-titles off

# Centre window list in the status bar
set -g status-justify absolute-centre

# Allow longer session names (default is 10, which truncates early)
set -g status-left-length 50

# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX}
set -g status-bg red
%endif

setw -g mode-keys emacs

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-features ",xterm*:RGB"

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"

# No bells at all
set -g bell-action none

# Keep windows around after they exit
set -g remain-on-exit off

# Turn the mouse on, but without copy mode dragging
set -g mouse on

# Some extra key bindings to select higher numbered windows
bind F1 selectw -t:10
bind F2 selectw -t:11
bind F3 selectw -t:12
bind F4 selectw -t:13
bind F5 selectw -t:14
bind F6 selectw -t:15
bind F7 selectw -t:16
bind F8 selectw -t:17
bind F9 selectw -t:18
bind F10 selectw -t:19
bind F11 selectw -t:20
bind F12 selectw -t:21

# A key to toggle between smallest and largest sizes if a window is visible in
# multiple places
bind F set -w window-size

# Keys to toggle monitoring activity in a window and the synchronize-panes option
bind m set monitor-activity
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

# Open splits and windows in the current pane's working directory.
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# Prompt for a session name, then create it.
# -A is optional: it switches to the session if the name already exists.
unbind-key i
bind-key i command-prompt -p "new session name:" { new-session -A -s "%%%" }

# Reuse [ and ] for session cycling
unbind-key [
unbind-key ]
bind-key [ switch-client -p
bind-key ] switch-client -n
