theme = "my_alabaster"

[editor]
line-number = "relative"
cursorline = true
auto-pairs = false

[keys.insert]
i = { i = "normal_mode" } 

[keys.normal]
[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
smart-case = false