local M = {}
local p = require("zen_alabaster.theme.palette")

local function hi(name, spec)
  vim.api.nvim_set_hl(0, name, spec)
end

local function link(name, target)
  hi(name, { link = target })
end

function M.apply()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = "zen_alabaster"

  hi("Normal", { fg = p.fg, bg = p.bg })
  hi("NormalFloat", { fg = p.fg_float, bg = p.bg_float })
  hi("FloatBorder", { fg = p.border, bg = p.bg_float })
  hi("LineNr", { fg = p.fg_dim })
  hi("CursorLineNr", { fg = p.definition })
  hi("CursorLine", { bg = p.bg_highlight })
  hi("ColorColumn", { bg = p.bg_highlight })
  hi("SignColumn", { fg = p.fg_dim, bg = p.bg })
  hi("StatusLine", { fg = p.definition, bg = p.status_bg })
  hi("StatusLineNC", { fg = p.fg_dim, bg = p.status_bg })
  hi("WinSeparator", { fg = p.border, bg = p.bg })
  hi("VertSplit", { fg = p.border, bg = p.bg })
  hi("Visual", { bg = p.selection })
  hi("VisualNOS", { bg = p.selection })
  hi("Search", { fg = p.fg, bg = p.bg_search })
  hi("IncSearch", { fg = p.bg, bg = p.definition })
  hi("MatchParen", { fg = p.definition, bg = p.bg_alt })
  hi("Pmenu", { fg = p.fg_float, bg = p.bg_alt })
  hi("PmenuSel", { fg = p.definition, bg = p.bg_popup })
  hi("PmenuSbar", { bg = p.bg_popup })
  hi("PmenuThumb", { bg = p.cursor })
  hi("Folded", { fg = p.fg_dim, bg = p.bg_alt })
  hi("FoldColumn", { fg = p.fg_dim, bg = p.bg })
  hi("NonText", { fg = p.border })
  hi("Whitespace", { fg = p.border })
  hi("EndOfBuffer", { fg = p.bg })
  hi("Directory", { fg = p.type })
  hi("Title", { fg = p.definition })

  hi("Comment", { fg = p.comment })
  hi("Constant", { fg = p.constant })
  hi("String", { fg = p.string })
  hi("Character", { fg = p.constant })
  hi("Number", { fg = p.numeric })
  hi("Boolean", { fg = p.constant })
  hi("Float", { fg = p.numeric })
  hi("Identifier", { fg = p.fg })
  hi("Function", { fg = p.fg })
  hi("Statement", { fg = p.fg })
  hi("Conditional", { fg = p.fg })
  hi("Repeat", { fg = p.fg })
  hi("Keyword", { fg = p.fg })
  hi("Operator", { fg = p.fg })
  hi("Exception", { fg = p.fg })
  hi("PreProc", { fg = p.fg })
  hi("Include", { fg = p.fg })
  hi("Define", { fg = p.definition })
  hi("Macro", { fg = p.definition })
  hi("Type", { fg = p.type })
  hi("StorageClass", { fg = p.fg })
  hi("Structure", { fg = p.type })
  hi("Typedef", { fg = p.type })
  hi("Special", { fg = p.fg })
  hi("SpecialChar", { fg = p.constant })
  hi("Delimiter", { fg = p.delimiter })
  hi("Underlined", { fg = p.definition, underline = true })
  hi("Todo", { fg = p.definition })

  hi("DiagnosticError", { fg = p.error })
  hi("DiagnosticWarn", { fg = p.warning })
  hi("DiagnosticInfo", { fg = p.info })
  hi("DiagnosticHint", { fg = p.hint })
  hi("DiagnosticUnderlineError", { undercurl = true, sp = p.error })
  hi("DiagnosticUnderlineWarn", { undercurl = true, sp = p.warning })
  hi("DiagnosticUnderlineInfo", { undercurl = true, sp = p.info })
  hi("DiagnosticUnderlineHint", { undercurl = true, sp = p.hint })
  hi("DiagnosticVirtualTextError", { fg = p.error, bg = p.bg_alt })
  hi("DiagnosticVirtualTextWarn", { fg = p.warning, bg = p.bg_alt })
  hi("DiagnosticVirtualTextInfo", { fg = p.info, bg = p.bg_alt })
  hi("DiagnosticVirtualTextHint", { fg = p.hint, bg = p.bg_alt })

  link("@comment", "Comment")
  link("@comment.documentation", "Comment")
  link("@constant", "Constant")
  link("@constant.builtin", "Constant")
  link("@constant.macro", "Macro")
  link("@string", "String")
  link("@string.escape", "Character")
  link("@string.regexp", "String")
  link("@string.special", "String")
  link("@number", "Number")
  link("@number.float", "Number")
  link("@boolean", "Boolean")
  link("@character", "Character")
  link("@keyword", "Keyword")
  link("@keyword.function", "Keyword")
  link("@keyword.operator", "Keyword")
  link("@keyword.return", "Keyword")
  link("@keyword.import", "Keyword")
  link("@keyword.repeat", "Keyword")
  link("@keyword.exception", "Keyword")
  link("@operator", "Operator")
  link("@punctuation", "Delimiter")
  link("@punctuation.delimiter", "Delimiter")
  link("@punctuation.bracket", "Delimiter")
  link("@punctuation.special", "Delimiter")
  link("@variable", "Identifier")
  link("@variable.builtin", "Identifier")
  link("@variable.parameter", "Identifier")
  link("@property", "Identifier")
  link("@field", "Identifier")
  link("@module", "Type")
  link("@namespace", "Type")
  link("@label", "Identifier")
  link("@type", "Type")
  link("@type.builtin", "Type")
  link("@type.qualifier", "Keyword")
  link("@constructor", "Type")
  link("@tag", "Type")
  link("@tag.attribute", "Type")
  link("@attribute", "Type")
  link("@function", "Function")
  link("@function.call", "Function")
  link("@function.builtin", "Function")
  link("@function.method", "Function")
  link("@function.method.call", "Function")
  link("@method", "Function")
  link("@method.call", "Function")
  hi("@function.definition", { fg = p.definition })
  hi("@function.method.definition", { fg = p.definition })
  hi("@constructor.definition", { fg = p.definition })
  hi("@type.definition", { fg = p.type })
  hi("@module.definition", { fg = p.type })

  link("@markup.heading", "Title")
  link("@markup.list", "Delimiter")
  link("@markup.quote", "Comment")
  link("@markup.raw", "String")
  link("@diff.plus", "DiagnosticHint")
  link("@diff.minus", "DiagnosticError")
  link("@diff.delta", "DiagnosticInfo")

  link("@lsp.type.comment", "Comment")
  link("@lsp.type.string", "String")
  link("@lsp.type.regexp", "String")
  link("@lsp.type.number", "Number")
  link("@lsp.type.operator", "Operator")
  link("@lsp.type.keyword", "Keyword")
  link("@lsp.type.modifier", "Keyword")
  link("@lsp.type.variable", "Identifier")
  link("@lsp.type.parameter", "Identifier")
  link("@lsp.type.property", "Identifier")
  link("@lsp.type.function", "Function")
  link("@lsp.type.method", "Function")
  link("@lsp.type.namespace", "Type")
  link("@lsp.type.type", "Type")
  link("@lsp.type.typeParameter", "Type")
  link("@lsp.type.class", "Type")
  link("@lsp.type.interface", "Type")
  link("@lsp.type.struct", "Type")
  link("@lsp.type.enum", "Type")
  link("@lsp.type.enumMember", "Constant")
  link("@lsp.type.decorator", "Type")
  link("@lsp.type.macro", "Macro")

  hi("@lsp.mod.deprecated", { strikethrough = true })
  hi("@lsp.typemod.function.declaration", { fg = p.definition })
  hi("@lsp.typemod.function.definition", { fg = p.definition })
  hi("@lsp.typemod.method.declaration", { fg = p.definition })
  hi("@lsp.typemod.method.definition", { fg = p.definition })
  hi("@lsp.typemod.class.declaration", { fg = p.type })
  hi("@lsp.typemod.class.definition", { fg = p.type })
  hi("@lsp.typemod.interface.declaration", { fg = p.type })
  hi("@lsp.typemod.interface.definition", { fg = p.type })
  hi("@lsp.typemod.struct.declaration", { fg = p.type })
  hi("@lsp.typemod.struct.definition", { fg = p.type })
  hi("@lsp.typemod.enum.declaration", { fg = p.type })
  hi("@lsp.typemod.enum.definition", { fg = p.type })
  hi("@lsp.typemod.type.declaration", { fg = p.type })
  hi("@lsp.typemod.type.definition", { fg = p.type })
  hi("@lsp.typemod.namespace.declaration", { fg = p.type })
  hi("@lsp.typemod.decorator.declaration", { fg = p.type })
  hi("@lsp.typemod.macro.declaration", { fg = p.definition })
  hi("@lsp.typemod.variable.readonly", { fg = p.constant })
  hi("@lsp.typemod.property.readonly", { fg = p.constant })
  hi("@lsp.typemod.enumMember.readonly", { fg = p.constant })
end

function M.setup()
  vim.cmd.colorscheme("zen_alabaster")
end

return M
