#https://docs.helix-editor.com/themes.html 
"ui.background" = { bg = "base3" }
"ui.text" = { fg = "base01" }

"comment" = { fg = "blue" }
"string" = { fg = "green" }
"constant" = { fg = "orange" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }

"ui.linenr.selected" = { bg = "base2" }
"ui.gutter" = { fg = "base1" }

"ui.statusline" = { fg = "base1", bg = "base2" }
"ui.statusline.inactive" = { bg = "base3" }

"ui.virtual.indent-guide" = { fg = "base2" }

"warning" =  { fg = "violet" }
"error" = { fg = "red" }
"info" = { fg = "base00" }
"hint" = { fg = "base00" }
"diagnostic.warning" = { fg = "violet" }
"diagnostic.error" = { fg = "red" }
"diagnostic.info" = { fg = "base00" }
"diagnostic.hint" = { fg = "base01" }

"ui.selection" = { fg = "cyan" }
"ui.menu.selected" = { fg = "cyan", bg = "base2"}

"ui.menu" = { fg = "base0", bg = "base2" }
"ui.help" = {fg="base0", bg="base2"}
"ui.popup" = { bg = "base2" }

"ui.cursorline" = { bg = "base2" }
"ui.cursor" = { fg = "base01", bg = "cyan" }

[palette]
base03   = "#002b36"
base02   = "#073642"
base01   = "#586e75"
base00   = "#657b83"
base0    = "#839496"
base1    = "#93a1a1"
base2    = "#eee8d5"
base3    = "#fdf6e3"

yellow  = "#b58900"
orange  = "#cb4b16"
red     = "#dc322f"
magenta = "#d33682"
violet  = "#6c71c4"
blue    = "#268bd2"
cyan    = "#2aa198"
green   = "#859900" 