[env]
# supports arbitrary env vars so rtx can be used like direnv/dotenv
NODE_ENV = 'production'

[tools]
# specify single or multiple versions
terraform = '1.0.0'
#erlang = ['23.3', '24.0']

# supports everything you can do with .tool-versions currently
nodejs = ['16']
#
## send arbitrary options to the plugin, passed as:
## RTX_TOOL_OPTS__VENV=.venv
## RTX_TOOL_OPTS__DEFAULT_PACKAGES__0=ansible
## RTX_TOOL_OPTS__DEFAULT_PACKAGES__1=pipenv
#python = {version='3.10', virtualenv='.venv', default_packages=['ansible', 'pipenv']}
#
#[plugins]
## specify a custom repo url
## note this will only be used if the plugin does not already exist
#python = 'https://github.com/jdxcode/rtx-python'
#
#[settings] # project-local settings
#verbose = true
#missing_runtime_behavior = 'warn'
#shims_dir = '~/.rtx/shims'
#
#[alias.nodejs] # project-local aliases
#my_custom_node = '18'