#+title My emacs configuration
#+PROPERTY: header-args:emacs-lisp  :tangle ./init.el
#+STARTUP: fold
* Philosopy of my configuratio
    Things I think Emacs will do for me:
    1. Note taking over multiple projects and support tasks - org mode
    2. Project navigation and handling - projectile magit forge
    3. Terminal - dired wrapping clis in transient state using elisp

    What im not using emacs to:
    1. IDE with lsp mode

 Workflow:
 - Do lots of filesystem stuff - dired
 - Git stuff - magit

* Things to investigate more
Understand the logic behind M-x C-x and C-c and C-u are thing under x always emacs basic while C-c more
comom for mode specific stuff?
* How to run this file
  Each code block has a \tangle\ to it, generate the code to files with M-x org-bable-tangle
  If no codeblocks get tangled, try M-x org-mode to reload

To update packages M-x list-packages then we will be prometed to type U for outdated packages, follow instructions

* Use-Package
** Details
:hook Package loaded first time one of the hooks are invoked
:bind Package loaded first time one of the keys are used
:commands Package loaded first time one of the commands are used
:mode Package loaded firt time a file with a prticular extension is opened
:after Package loaded after other package
:defer Default if no other option is used, will defaear loading till after startup
:demand t Package is loaded at startup

:config Is run after package is loaded

** Config
#+begin_src emacs-lisp
  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/") ;; Get latest org mode
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
   (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
     (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t) ; Install packages if they are not avaliable already
  ;; (setq use-package-verbose t) ; uncomment for debugging config, prints more to messages buffer
  ; To update the package list use M-x list-packages this can be good if i get error trying to instal new packages
  ; C-h f function v variable k keybinding h general help

#+end_src

* Start with tweeking the GC
#+begin_src emacs-lisp
    (use-package gcmh
  :ensure t
  :demand t
  :config
  (gcmh-mode 1))
#+end_src
* Basic UI Configuration
** General
#+begin_src emacs-lisp

  ;; Cleanup Emacs user interface
  (setq inhibit-startup-message t)

  (scroll-bar-mode -1) ; Disable visible scrollbar
  (tool-bar-mode -1)  ; Disable the toolbar
  (tooltip-mode -1) ; Disable tooltips
  (set-fringe-mode 10)
  (menu-bar-mode -1) ; Disable the menu bar
  (setq visible-bell t) ; Turn off sound and show flashing warning instead
#+end_src

** Font configuration
Install Fira Code
https://dev.to/josuerodriguez98/installing-firacode-on-windows-and-ubuntu-1fn1
#+begin_src emacs-lisp
(set-face-attribute 'default nil :family "Fira Code" :height 140 :weight 'normal)
#+end_src

** Theme
#+begin_src emacs-lisp
(load-theme 'tango-dark)
#+end_src

* Which Key
#+begin_src emacs-lisp
(use-package which-key
  :defer 0
  :diminish which-key-mode
  :config
  (which-key-mode)
  (setq which-key-idle-delay 1))
#+end_src
* Ivy
#+begin_src emacs-lisp

; Using M-o while inside a ivy buffer shows any special things one can do in that buffer
; Using C-c C-o persist an ivy search buffer for example with ripgrep
(use-package counsel
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)	
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :init (ivy-mode 1))
#+end_src
* Evil
#+begin_src emacs-lisp
(use-package evil
  :init
  (setq evil-want-keybinding nil)
  (setq evil-want-integration t)
  :config
  (evil-mode 1)
  (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

(use-package evil-commentary
  :after evil
  :config
  (evil-commentary-mode))
#+end_src
* Projectile
#+begin_src emacs-lisp

  ; Serch projects p search f search files sr search using rg xe eshell q switch between open projects
  ; Depends of fd and ripgrep
  ; Add shortcut to open projet in idea
  (use-package projectile
    :custom ((projectile-completion-system 'ivy))
    :bind ("C-SPC" . projectile-commander)
  ;  :bind-keymap
  ;  ("C-c p" . projectile-command-map)
    :config
    (projectile-mode)
  (def-projectile-commander-method ?s
    "Open a *shell* buffer for the project."
    (projectile-run-eshell))

  (def-projectile-commander-method ?c
    "Run `compile' in the project."
    (projectile-compile-project nil))

  (def-projectile-commander-method ?p
    "Project selection."
    (projectile-switch-project))

  (def-projectile-commander-method ?d
    "Open project root in dired."
    (projectile-dired))

  (def-projectile-commander-method ?j
    "Jump to project buffer."
    (projectile-switch-to-buffer))

  (def-projectile-commander-method ?/
    "rg project"
    (counsel-rg))
    ;; NOTE: Set this to the folder where you keep your Git repos!
  ;  (setq projectile-create-missing-test-files t)
    :init
    (when (file-directory-p "~/repos")
      (setq projectile-project-search-path '("~/repos")))
    (setq projectile-switch-project-action #'projectile-commander)
    ;(setq projectile-switch-project-action #'projectile-commander) ; First thing to happen when switching project
    )
#+end_src

* ELisp
What is the recommended elisp dev setup?
Completion = completion-at-point M-<TAB>
Diagnostics = Using flymake-mode - flymake-show-buffer-diagnostic
Go to reference xref-find-references gd and gr in evil works out of the box
Formatting?
https://github.com/p3r7/awesome-elisp
https://dawranliou.com/blog/structural-editing-in-vanilla-emacs/
#+begin_src emacs-lisp
  (add-hook 'emacs-lisp-mode-hook 'flymake-mode)

  (setq flymake-log-level 'warning)

#+end_src
* Magit/Forge
#+begin_src emacs-lisp
  (use-package magit
     :custom
     (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1)
  )

  (use-package forge
    :after magit)
#+end_src
* Org Mode
  M-x org-agenda OR org-agenda-list
   C-c [ ] add/remove file to files to agenda
   HABBIT exlude org file from all projects in som global gitignore
  add org files for all projects add them to agenda and track what im doing in the projects
   understand todo list items state done C-c t. called task and task state in org?
   IVESTIGATE capture template and structure templates M-x org-capture quicker then creating todo stuff manually
  Video manage your life with org
  https://www.youtube.com/watch?v=VcgjTEa0kU4&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&index=5
  https://www.youtube.com/watch?v=PNE-mgkZ6HM&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&index=6
  Video configure all dot files with Org Babel
  https://www.youtube.com/watch?v=kkqVTDbfYp4&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&index=7
  Make better symlinks babel generate files that i symlink, i also commit the generated files
  https://www.gnu.org/software/stow/ use this to create symlinks
#+begin_src emacs-lisp
      (defun fav/org-mode-setup ()
	  (visual-line-mode 1) ; Make text wrap when at the end of window
  )
      (use-package org
	:custom ; dont use setq in config use custom instead!
	;; (org-agenda-files '("~/orgfiles/tasks.org"))
	(org-confirm-babel-evaluate nil) ; dont have to confirm each execute block
	(org-agenda-start-with-log-mode t)
	(org-log-done 'time)
	:hook (org-mode . fav/org-mode-setup)
	:config
	(require 'org-tempo)
       (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
	(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp")) ; <el <TAB>
	)
#+end_src
** Configure Babel Languages
#+begin_src emacs-lisp
; C-c C-c eval block of code
(org-babel-do-load-languages 'org-babel-load-languages
			     '((emacs-lisp . t)))
#+end_src

* Dired

Dired is a built-in file manager for Emacs that does some pretty amazing things!  Here are some key bindings you should try out:
WK Indicate that I get which key, they have sub commands.

** Key Bindings

**** Navigation

*Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - WK Mark files in buffer using regular expression
- =*= - WK Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

** Configuration

#+begin_src emacs-lisp
   ;(add-hook 'dired-load-hook
   ;           (function (lambda () (load "dired-x"))))

    (use-package dired
      :ensure nil
      :commands (dired dired-jump)
      :bind (("C--" . dired-jump))
      :config
      (evil-collection-define-key 'normal 'dired-mode-map
	"h" 'dired-single-up-directory
	"l" 'dired-single-buffer) ;; do i want l to open file in preview so i can close it with q then use ret to open file
  ) 

  ; Prevent opening new buffers all the time
    (use-package dired-single
      :commands (dired dired-jump))

    (use-package dired-hide-dotfiles
;      :hook (dired-mode . dired-hide-dotfiles-mode)
      :config
      (evil-collection-define-key 'normal 'dired-mode-map
	"H" 'dired-hide-dotfiles-mode))

#+end_src
* Eshell
Show eshell at startup
#+begin_src emacs-lisp
    (defun fav/configure-eshell ()
    ;; Save command history when commands are entered
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    ;; Bind some useful keys for evil-mode
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "C-r") 'counsel-esh-history)
    (evil-normalize-keymaps)

    (setq eshell-history-size         10000
	  eshell-buffer-maximum-lines 10000
	  eshell-hist-ignoredups t ; dont put consecutive commands in history
	  eshell-scroll-to-bottom-on-input t))

  (use-package eshell
    :hook (eshell-first-time-mode . fav/configure-eshell)
  :custom (eshell-banner-message "")
    :config

    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t)
      (setq eshell-visual-commands '("htop" "zsh" "vim")))
    )

     (add-hook 'emacs-startup-hook #'eshell)
#+end_src
* Custom keybinding
#+begin_src emacs-lisp
  (defun fav/toggle-buffer ()
    "Flips to the last-visited buffer in this window."
    (interactive)
    (switch-to-buffer (other-buffer (current-buffer))))


  ;; Make killing current buffer faster
  ;; (global-set-key (kbd "M-SPC") 'execute-extended-command)
  (global-set-key (kbd "C-x k") 'kill-this-buffer)

  (global-set-key (kbd "C-;") 'other-window)
  (global-set-key (kbd "M-;") 'fav/toggle-buffer)

  (global-set-key (kbd "C-'") 'counsel-org-agenda-headlines) 
  (global-set-key (kbd "M-'") 'org-agenda-list)
  (global-set-key (kbd "C-M-'") 'org-agenda) 

  ;(define-key KEYMAP KEY DEF)
#+end_src

#+RESULTS:
: dired-jump

* AI assistance
** Chat GPT
Start with gptel or do 
Run with C-c <RET>
Put my api key in a file as shown below
#+begin_src emacs-lisp
(defun fav/read-openai-key ()
  (with-temp-buffer
    (insert-file-contents "~/key.txt")
    (string-trim (buffer-string))))

(use-package gptel
  :init
  (setq-default gptel-model "gpt-3.5-turbo"
                gptel-playback t
                gptel-default-mode 'org-mode
                gptel-api-key #'fav/read-openai-key))
#+end_src
* My packages
Load all my stuff that are local for this machine in custom.el.

Start with something like this in custom.el

(defun am-i-here ()
  (interactive)
  (message "im here"))

(provide 'custom)
#+begin_src emacs-lisp
  (when (file-exists-p "~/.emacs.d/custom-packages/custom.el")
   (add-to-list 'load-path "~/.emacs.d/custom-packages")
   (require 'my-custom))
#+end_src
