#+title My emacs configuration
#+PROPERTY: header-args:emacs-lisp  :tangle ./init.el
#+STARTUP: fold
* Philosopy of my configuratio
    Things I think Emacs will do for me:
    1. Note taking over multiple projects and support tasks - org mode
    2. Project navigation and handling - projectile magit forge
    3. Terminal - dired wrapping clis in transient state using elisp

    What im not using emacs to:
    1. IDE with lsp mode

 Workflow:
 - Do lots of filesystem stuff - dired
 - Git stuff - magit

* Things to investigate more
Understand the logic behind M-x C-x and C-c and C-u are thing under x always emacs basic while C-c more
comom for mode specific stuff?
* How to run this file
  Each code block has a \tangle\ to it, generate the code to files with M-x org-bable-tangle
  If no codeblocks get tangled, try M-x org-mode to reload

To update packages M-x list-packages then we will be prometed to type U for outdated packages, follow instructions

* Use-Package
** Details
:hook Package loaded first time one of the hooks are invoked
:bind Package loaded first time one of the keys are used
:commands Package loaded first time one of the commands are used
:mode Package loaded firt time a file with a prticular extension is opened
:after Package loaded after other package
:defer Default if no other option is used, will defaear loading till after startup
:demand t Package is loaded at startup

:config Is run after package is loaded

** Config
#+begin_src emacs-lisp
  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/") ;; Get latest org mode
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
   (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
     (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t) ; Install packages if they are not avaliable already
  ;; (setq use-package-verbose t) ; uncomment for debugging config, prints more to messages buffer
  ; To update the package list use M-x list-packages this can be good if i get error trying to instal new packages
  ; C-h f function v variable k keybinding h general help

#+end_src

* Start with tweeking the GC
#+begin_src emacs-lisp
    (use-package gcmh
  :ensure t
  :demand t
  :config
  (gcmh-mode 1))
#+end_src
* Basic UI Configuration
** General
#+begin_src emacs-lisp

  ;; Cleanup Emacs user interface
  (setq inhibit-startup-message t)

  (scroll-bar-mode -1) ; Disable visible scrollbar
  (tool-bar-mode -1)  ; Disable the toolbar
  (tooltip-mode -1) ; Disable tooltips
  (set-fringe-mode 10)
  (menu-bar-mode -1) ; Disable the menu bar
  (setq visible-bell t) ; Turn off sound and show flashing warning instead
#+end_src

** Font configuration
Install Fira Code
https://dev.to/josuerodriguez98/installing-firacode-on-windows-and-ubuntu-1fn1
#+begin_src emacs-lisp
(set-face-attribute 'default nil :family "Fira Code" :height 140 :weight 'normal)
#+end_src

** Theme
#+begin_src emacs-lisp
(load-theme 'tango-dark)
#+end_src

* Which Key
#+begin_src emacs-lisp
(use-package which-key
  :defer 0
  :diminish which-key-mode
  :config
  (which-key-mode)
  (setq which-key-idle-delay 1))
#+end_src
* Ivy
#+begin_src emacs-lisp

; Using M-o while inside a ivy buffer shows any special things one can do in that buffer
; Using C-c C-o persist an ivy search buffer for example with ripgrep
(use-package counsel
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)	
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :init (ivy-mode 1))
#+end_src
* Projectile
#+begin_src emacs-lisp

  ; Serch projects p search f search files sr search using rg xe eshell q switch between open projects
  ; Depends of fd and ripgrep
  ; Add shortcut to open projet in idea
  (use-package projectile
    :custom ((projectile-completion-system 'ivy))
    :bind ("M-SPC" . projectile-commander)
  ;  :bind-keymap
  ;  ("C-c p" . projectile-command-map)
    :config
    (projectile-mode)
  (def-projectile-commander-method ?s
    "Open a *shell* buffer for the project."
    (projectile-run-eshell))

  (def-projectile-commander-method ?c
    "Run `compile' in the project."
    (projectile-compile-project nil))

  (def-projectile-commander-method ?p
    "Project selection."
    (projectile-switch-project))

  (def-projectile-commander-method ?d
    "Open project root in dired."
    (projectile-dired))

  (def-projectile-commander-method ?j
    "Jump to project buffer."
    (projectile-switch-to-buffer))

  (def-projectile-commander-method ?/
    "rg project"
    (counsel-rg))
    ;; NOTE: Set this to the folder where you keep your Git repos!
  ;  (setq projectile-create-missing-test-files t)
    :init
    (when (file-directory-p "~/repos")
      (setq projectile-project-search-path '(("~/repos" . 2))))
    (setq projectile-switch-project-action #'projectile-commander)
    )
#+end_src
* Lisp
** Lispy
#+begin_src emacs-lisp
  (use-package lispy)
  (add-hook 'emacs-lisp-mode-hook (lambda () (lispy-mode 1)))
#+end_src
* Programming languages
** ELisp
What is the recommended elisp dev setup?
Completion = completion-at-point M-<TAB> C-M-i??
Diagnostics = Using flymake-mode - flymake-show-buffer-diagnostic
Go to reference xref-find-references
Formatting?
https://github.com/p3r7/awesome-elisp
https://dawranliou.com/blog/structural-editing-in-vanilla-emacs/
#+begin_src emacs-lisp
  (add-hook 'emacs-lisp-mode-hook 'flymake-mode)

  (setq flymake-log-level 'warning)

#+end_src
** Yaml
#+begin_src emacs-lisp
(use-package yaml-mode)
#+end_src
* Magit/Forge
** Setup
Note the below setup is tailored to work with my projectile setup to find projects.
- Set different user.name and user.email for different repos
In ~/.gitconfig set the folowing.
#+begin_src 
[includeIf "gitdir:~/repos/<customer 1>/**/.git"]
	   path = .gitconfig-<customer 1>
[includeIf "gitdir:~/repos/<customer 2>/**/.git"]
	   path = .gitconfig-<customer 2>
[includeIf "gitdir:~/repos/private/**/.git"]
	   path = .gitconfig-private
#+end_src
Then in each .gitconfig-<post-fix> set what should be included.
#+begin_src 
[user]
	email = henke@henkelarsson.se
	name = Henrik Larsson
#+end_src
- Use multiple ssh keys for multiple repos on same machine
[[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][Generate an ssh key]]
#+begin_src 

#+end_src
And update your ~/.ssh/config to something like.
How to handle if I want to use different ssh keys and they all have git@github.com url?
#+begin_src 
Host github.com
    HostName github.com
    IdentitiesOnly yes

Match host github.com user git
    # Set your private SSH key, this will match all repos cloned with git@github.com.
    IdentityFile ~/.ssh/myprivategitrepo

# Check the repo file .git/config under url to check what user is used to clone the repo.
Match host github.com user <company 1 user>
    IdentityFile ~/.ssh/id_github_<company 1 user>

Match host github.com user <company 2 user>
    IdentityFile ~/.ssh/id_github_org_<company 2 user>
#+end_src
- Have forge use multiple github repos
[[https://magit.vc/manual/forge/Getting-Started.html][Follow instructions]]
** Configuration
#+begin_src emacs-lisp
  (use-package magit
     :custom
     (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1)
  )

  (use-package forge
    :after magit)
(setq auth-sources '("~/.authinfo")) ; Set where api key is stored for forge, check dock for format
#+end_src
* Org Mode
** Basic
  M-x org-agenda OR org-agenda-list
   C-c [ ] add/remove file to files to agenda
   HABBIT exlude org file from all projects in som global gitignore
  add org files for all projects add them to agenda and track what im doing in the projects
   understand todo list items state done C-c t. called task and task state in org?
   IVESTIGATE capture template and structure templates M-x org-capture quicker then creating todo stuff manually
  Video manage your life with org
  https://www.youtube.com/watch?v=VcgjTEa0kU4&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&index=5
  https://www.youtube.com/watch?v=PNE-mgkZ6HM&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&index=6
  Video configure all dot files with Org Babel
  https://www.youtube.com/watch?v=kkqVTDbfYp4&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&index=7
  Make better symlinks babel generate files that i symlink, i also commit the generated files
  https://www.gnu.org/software/stow/ use this to create symlinks
#+begin_src emacs-lisp
	(defun fav/org-mode-setup ()
	    (visual-line-mode 1) ; Make text wrap when at the end of window
    )
	(use-package org
	  :custom ; dont use setq in config use custom instead!
	  (org-agenda-files '("~/roam-notes/"))
	  (org-confirm-babel-evaluate nil) ; dont have to confirm each execute block
	  (org-agenda-start-with-log-mode t)
	  (org-log-done 'time)
    (org-agenda-span 'day)
	  :hook (org-mode . fav/org-mode-setup)
	  :bind
	  (("M-'" . org-agenda)
           ("C-M-'" . counsel-org-agenda-headlines))
	  :config
	  (require 'org-tempo)
	 (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
	  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp")) ; <el <TAB>
	  )
#+end_src
** Org Roam
#+begin_src emacs-lisp
		      (use-package org-roam
		    :custom
		  (org-roam-directory "~/roam-notes")
	(org-roam-completion-everywhere t)
		:bind
      (("C-c n l" . org-roam-buffer-toggle)
	      ("C-c n f" . org-roam-node-find)
	      ("C-'" . org-roam-node-find)
	    ("C-c n i" . org-roam-node-insert))
	  :config
	(org-roam-setup))
#+end_src
** Configure Babel Languages
#+begin_src emacs-lisp
; C-c C-c eval block of code
(org-babel-do-load-languages 'org-babel-load-languages
			     '((emacs-lisp . t)))
#+end_src

** Webserver to serve a site
M-x httpd-serve-directory
For example to serve my site use path =public/= and go to =http://localhost8080=
#+begin_src emacs-lisp
  (use-package simple-httpd)
#+end_src
* Dired
** Configuration

#+begin_src emacs-lisp
    (use-package dired
      :ensure nil
      :bind (("C--" . dired-jump))) 

#+end_src
* Eshell
Show eshell at startup
#+begin_src emacs-lisp
    (defun fav/configure-eshell ()
    ;; Save command history when commands are entered
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    (setq eshell-history-size         10000
	  eshell-buffer-maximum-lines 10000
	  eshell-hist-ignoredups t ; dont put consecutive commands in history
	  eshell-scroll-to-bottom-on-input t))

  (use-package eshell
    :hook (eshell-first-time-mode . fav/configure-eshell)
  :custom (eshell-banner-message "")
    :config

    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t)
      (setq eshell-visual-commands '("htop" "zsh" "vim")))
    )

     (add-hook 'emacs-startup-hook #'eshell)
#+end_src
* Custom keybinding
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x k") 'kill-this-buffer)
#+end_src
* AI assistance
** Chat GPT
Start with gptel or do 
Run with C-c <RET>
Put my api key in a file as shown below
#+begin_src emacs-lisp
(defun fav/read-openai-key ()
  (with-temp-buffer
    (insert-file-contents "~/key.txt")
    (string-trim (buffer-string))))

(use-package gptel
  :init
  (setq-default gptel-model "gpt-3.5-turbo"
                gptel-playback t
                gptel-default-mode 'org-mode
                gptel-api-key #'fav/read-openai-key))
#+end_src
* My packages
Load all my stuff that are local for this machine in custom.el.

Start with something like this in custom.el

(defun am-i-here ()
  (interactive)
  (message "im here"))

(provide 'custom)
#+begin_src emacs-lisp
  (when (file-exists-p "~/.emacs.d/custom-packages/custom.el")
   (add-to-list 'load-path "~/.emacs.d/custom-packages")
   (require 'my-custom))
#+end_src

* Completion
f1 show docs
C-w show source
#+begin_src emacs-lisp
  (use-package company
    :init
    (add-hook 'after-init-hook 'global-company-mode))

  (global-set-key (kbd "C-\\") 'company-complete)
#+end_src

* Avy
#+begin_src emacs-lisp
  (use-package avy
    :init
    (avy-setup-default)
    (global-set-key (kbd "C-;") 'avy-goto-char-timer))
#+end_src
