local api = vim.api
local uv = vim.uv or vim.loop

local M = {}

local defaults = {
	command = "broot",
	replace_netrw = true,
	conf_path = function()
		return vim.fs.joinpath(vim.fn.stdpath("cache"), "broot.nvim.hjson")
	end,
}

local state = {
	augroup = nil,
	commands_created = false,
	setup_done = false,
	opts = vim.deepcopy(defaults),
}

local function cwd()
	return (uv.cwd and uv.cwd()) or vim.fn.getcwd()
end

local function normalize(path)
	if not path or path == "" then
		return vim.fs.normalize(cwd())
	end

	local expanded = vim.fn.expand(path)
	if expanded == "" then
		expanded = path
	end

	return vim.fs.normalize(vim.fn.fnamemodify(expanded, ":p"))
end

local function is_directory(path)
	return path ~= nil and path ~= "" and vim.fn.isdirectory(path) == 1
end

local function executable()
	return vim.fn.executable(state.opts.command) == 1
end

local function notify(msg, level)
	vim.notify(msg, level or vim.log.levels.INFO, { title = "broot.nvim" })
end

local function current_file_path()
	if vim.bo.buftype == "terminal" then
		return cwd()
	end

	local name = api.nvim_buf_get_name(0)
	if name == "" then
		return cwd()
	end

	return normalize(name)
end

local function current_file_dir()
	local path = current_file_path()
	if is_directory(path) then
		return path
	end
	return vim.fs.dirname(path)
end

local function delete_buffer(bufnr)
	if not bufnr or not api.nvim_buf_is_valid(bufnr) then
		return
	end
	pcall(api.nvim_buf_delete, bufnr, { force = true })
end

local function ensure_conf_path()
	local conf_path = state.opts.conf_path
	if type(conf_path) == "function" then
		conf_path = conf_path()
	end

	conf_path = normalize(conf_path)
	local conf_dir = vim.fs.dirname(conf_path)
	if conf_dir and vim.fn.isdirectory(conf_dir) == 0 then
		vim.fn.mkdir(conf_dir, "p")
	end

	local contents = table.concat({
		"# This file is generated by lua/broot.lua.",
		"verbs: [",
		"    {",
		"        invocation: __nvim_broot_open",
		"        apply_to: any",
		'        cmd: ":write_output {file}	{line};:quit"',
		"    }",
		"]",
		"",
	}, "\n")

	local existing = ""
	if vim.fn.filereadable(conf_path) == 1 then
		existing = table.concat(vim.fn.readfile(conf_path), "\n")
	end

	if existing ~= contents then
		vim.fn.writefile(vim.split(contents, "\n", { plain = true }), conf_path)
	end

	return conf_path
end

local function conf_arg()
	local paths = {}
	local xdg = vim.env.XDG_CONFIG_HOME
	if not xdg or xdg == "" then
		xdg = vim.fs.joinpath(vim.fn.expand("~"), ".config")
	end

	local default_conf = vim.fs.joinpath(xdg, "broot", "conf.hjson")
	if vim.fn.filereadable(default_conf) == 1 then
		table.insert(paths, vim.fs.normalize(default_conf))
	end

	table.insert(paths, ensure_conf_path())
	return table.concat(paths, ";")
end

local function clear_netrw_autocmds()
	pcall(api.nvim_clear_autocmds, { group = "FileExplorer" })
end

local launch

local function open_paths_from_output(out_path)
	if vim.fn.filereadable(out_path) ~= 1 then
		return false
	end

	local lines = vim.fn.readfile(out_path)
	vim.fn.delete(out_path)

	if #lines == 0 then
		return false
	end

	local selection = lines[1]
	if not selection or selection == "" then
		return false
	end

	selection = selection:gsub("\\t", "\t")

	local path, line = selection:match("^(.-)\t(%d+)$")
	if not path then
		path = selection
	end

	local normalized = normalize(path)
	if normalized == "" then
		return false
	end

	if is_directory(normalized) then
		launch(normalized, { notify_on_empty = false })
		return true
	end

	vim.cmd.edit(vim.fn.fnameescape(normalized))

	if line then
		pcall(api.nvim_win_set_cursor, 0, { math.max(1, tonumber(line) or 1), 0 })
	end

	return true
end

launch = function(path, opts)
	opts = opts or {}

	if not executable() then
		notify(("`%s` is not executable"):format(state.opts.command), vim.log.levels.ERROR)
		return
	end

	local previous_buf = api.nvim_get_current_buf()
	local target = normalize(path)
	local out_path = vim.fn.tempname()
	local job_id

	vim.cmd.enew()

	local term_buf = api.nvim_get_current_buf()
	vim.bo[term_buf].bufhidden = "wipe"
	vim.bo[term_buf].swapfile = false
	vim.b[term_buf].broot_terminal = true

	local function send_open_key()
		vim.fn.chansend(job_id, ":__nvim_broot_open\r")
	end

	if opts.delete_previous then
		delete_buffer(previous_buf)
	end

	local cmd = { state.opts.command, "--conf", conf_arg(), "--verb-output", out_path, target }
	job_id = vim.fn.termopen(cmd, {
		on_exit = function(_, code, _)
			vim.schedule(function()
				local opened = false
				if code == 0 then
					opened = open_paths_from_output(out_path)
				elseif vim.fn.filereadable(out_path) == 1 then
					vim.fn.delete(out_path)
				end

				delete_buffer(term_buf)

				if code ~= 0 then
					return
				end

				if not opened and opts.notify_on_empty ~= false then
					notify("broot exited without selecting a file")
				end
			end)
		end,
	})

	if job_id <= 0 then
		notify("failed to start broot", vim.log.levels.ERROR)
		delete_buffer(term_buf)
		return
	end

	vim.keymap.set("t", "<CR>", send_open_key, {
		buffer = term_buf,
		silent = true,
		desc = "Open selection in broot",
	})

	vim.cmd.startinsert()
	return job_id
end

local function replace_directory_buffer(path)
	local target = normalize(path)
	if not is_directory(target) then
		return
	end

	clear_netrw_autocmds()
	return launch(target, { delete_previous = true, notify_on_empty = false })
end

local function should_replace_startup_directory()
	if not state.opts.replace_netrw then
		return false
	end

	if vim.fn.argc() ~= 1 then
		return false
	end

	return is_directory(normalize(vim.fn.argv(0)))
end

function M.open(path)
	local target = path
	if not target or target == "" then
		target = current_file_path()
	end

	return launch(target)
end

function M.open_current_file_dir()
	return launch(current_file_dir())
end

function M.open_working_directory()
	return launch(cwd())
end

function M.create_commands()
	if state.commands_created then
		return
	end

	api.nvim_create_user_command("Broot", function(args)
		M.open(args.args)
	end, {
		nargs = "?",
		complete = "file",
		desc = "Open broot",
	})

	api.nvim_create_user_command("BrootCurrentFile", function()
		M.open(current_file_path())
	end, {
		desc = "Open broot rooted at the current file",
	})

	api.nvim_create_user_command("BrootCurrentDirectory", function()
		M.open_current_file_dir()
	end, {
		desc = "Open broot rooted at the current file directory",
	})

	api.nvim_create_user_command("BrootWorkingDirectory", function()
		M.open_working_directory()
	end, {
		desc = "Open broot rooted at the working directory",
	})

	state.commands_created = true
end

function M.setup_autocmds()
	state.augroup = api.nvim_create_augroup("broot.nvim", { clear = true })

	api.nvim_create_autocmd("VimEnter", {
		group = state.augroup,
		callback = function()
			if should_replace_startup_directory() then
				replace_directory_buffer(vim.fn.argv(0))
			end
		end,
	})
end

function M.setup(opts)
	if state.setup_done then
		return
	end

	state.opts = vim.tbl_deep_extend("force", vim.deepcopy(defaults), opts or {})

	M.create_commands()
	M.setup_autocmds()

	state.setup_done = true
end

return M
