name: Build and Publish Container

on:
  workflow_dispatch:
  push:
    paths:
      - distroboxes/TumbleweedL1emacs

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: distroboxes/
        file: distroboxes/TumbleweedL1emacs
        push: true
        tags: ${{ github.repository_owner }}/${{ github.event.repository.name }}-tumbleweedemacs:latest

