name: Build and Publish Container

on:
  push:
    paths:
      - distroboxes/TumbleweedL1emacs

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract git commit SHA
      id: extract-sha
      run: echo "GIT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: distroboxes/
        file: distroboxes/TumbleweedL1emacs
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/tumbleweedemacs:${{ env.GIT_SHA }}
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/tumbleweedemacs:latest
