name: check
# Todo i should run org-bable-tangle in action and add the init.el file as an artifact here then create come up with a smart way to use it locally, or maybe add the file to my repo with a pr after check is ok?

on:
  push:
    branches:
      - master
    paths: ./emacs

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 28.2
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        check: load-file
        file: ./emacs/init.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
    - uses: leotaku/elisp-check@master
      with:
        check: byte-compile
        file: ./emacs/init.el
        ignore_warnings: ${{ matrix.ignore_warnings }}